# ===================================
#  Relation Behavior Config
# ===================================

categoryslugs:
    label: Slugs
    view:
        list: $/dynamedia/posts/models/categoryslug/columns.yaml
        toolbarButtons: unlink
    manage:
        form: $/dynamedia/posts/models/categoryslug/fields.yaml
        recordsPerPage: 10

translations:
    label: Translations
    view:
        list: $/dynamedia/posts/models/categorytranslation/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/dynamedia/posts/models/categorytranslation/fields.yaml
        recordsPerPage: 10
