# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Treetest

# Model Form Field configuration
form: $/dynamedia/posts/models/treetest/fields.yaml

# Model Class name
modelClass: Dynamedia\Posts\Models\Treetest

# Default redirect location
defaultRedirect: dynamedia/posts/treetest

# Create page
create:
    title: backend::lang.form.create_title
    redirect: dynamedia/posts/treetest/update/:id
    redirectClose: dynamedia/posts/treetest

# Update page
update:
    title: backend::lang.form.update_title
    redirect: dynamedia/posts/treetest
    redirectClose: dynamedia/posts/treetest

# Preview page
preview:
    title: backend::lang.form.preview_title
