scopes:
    categories:
        label: Categories
        modelClass: Dynamedia\Posts\Models\Category
        scope: applyWhereHasCategories
        nameFrom: name
        valueFrom: id

    tags:
        label: Tags
        modelClass: Dynamedia\Posts\Models\Tag
        scope: applyWhereHasTags
        nameFrom: name
        valueFrom: id

    hide_published:
        label: Hide Published
        scope: applyIsNotPublished
        type: checkbox

    author_by_profile:

    editor_by_profile:

    published_at:
        label: Publishing Date
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'



