# ===================================
#  Relation Behavior Config
# ===================================

translations:
    label: Translations
    view:
        list: $/dynamedia/posts/models/posttranslation/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/dynamedia/posts/models/posttranslation/fields.yaml
        recordsPerPage: 10

postslugs:
    label: Slugs
    view:
        list: $/dynamedia/posts/models/postslug/columns.yaml
        toolbarButtons: unlink
    manage:
        form: $/dynamedia/posts/models/postslug/fields.yaml
        recordsPerPage: 10
