# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dynamedia.posts::lang.tagslugs.titles.tagslug

# Model Form Field configuration
form: $/dynamedia/posts/models/tagslug/fields.yaml

# Model Class name
modelClass: Dynamedia\Posts\Models\TagSlug

# Default redirect location
defaultRedirect: dynamedia/posts/tagslugs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: dynamedia/posts/tagslugs/update/:id
    redirectClose: dynamedia/posts/tagslugs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: dynamedia/posts/tagslugs
    redirectClose: dynamedia/posts/tagslugs

# Preview page
preview:
    title: backend::lang.form.preview_title
