tabs:
    fields:
        content:
            tab: dynamedia.posts::lang.common.tabs.main
            label: dynamedia.posts::lang.common.labels.block_content
            type: richeditor
            size: huge

        image:
            tab: dynamedia.posts::lang.common.tabs.image
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/image/body_section.yaml
