tabs:
    fields:
        cms_partial:
            label: dynamedia.posts::lang.blocks.labels.cms_partial
            tab: dynamedia.posts::lang.common.tabs.main
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getCmsPartialOptions
        data:
            label: Pass variables to the partial
            tab: Data
            type: repeater
            form:
                fields:
                    key:
                        label: Key
                        span: left
                    value:
                        label: Value
                        span: right

        in_contents:
            tab: dynamedia.posts::lang.common.tabs.settings
            type: switch
            label: dynamedia.posts::lang.blocks.labels.in_contents
            default: true

        heading:
            tab: dynamedia.posts::lang.common.tabs.settings
            span: left
            label: dynamedia.posts::lang.blocks.labels.section_heading

        sId:
            tab: dynamedia.posts::lang.common.tabs.settings
            span: right
            label: dynamedia.posts::lang.blocks.labels.section_id
            preset: heading
