tabs:
  fields:
    cms_content:
      label: dynamedia.posts::lang.blocks.labels.cms_content
      tab: dynamedia.posts::lang.common.tabs.main
      type: dropdown
      options: \Dynamedia\Posts\Classes\Helpers\Form::getCmsContentOptions

    in_contents:
        tab: dynamedia.posts::lang.common.tabs.settings
        type: switch
        label: dynamedia.posts::lang.blocks.labels.in_contents
        default: true

    heading:
         tab: dynamedia.posts::lang.common.tabs.settings
         span: left
         label: dynamedia.posts::lang.blocks.labels.section_heading

    sId:
         tab: dynamedia.posts::lang.common.tabs.settings
         span: right
         label: dynamedia.posts::lang.blocks.labels.section_id
         preset: heading
