tabs:
    fields:
        operator_type:
            tab: Detail
            label: Operator Type
            type: dropdown
            options:
                person: Person / Individual
                organization: Organization
        name:
            tab: Detail
            label: Name

        logo:
            tab: Detail
            label: Logo
            type: mediafinder

        address_street:
            tab: Address
            label: Street Address

        address_city:
            tab: Address
            label: City

        address_region:
            tab: Address
            label: Region

        address_postal_code:
            tab: Address
            label: Postal Code

        address_country:
            tab: Address
            label: Country

        address_latitude:
            tab: Address
            label: Latitude

        address_longitude:
            tab: Address
            label: Longitude

        contact_telephone:
            tab: Contact
            label: Telephone

        contact_email:
            tab: Contact
            label: Email

        contact_fax:
            tab: Contact
            label: Fax

        social_facebook:
            tab: Social
            label: Facebook URL

        social_twitter:
            tab: Social
            label: Twitter Handle
            placeholder: '@DynamediaUK'
