secondaryTabs:
    fields:
        schema_about:
            tab: About
            type: repeater
            # group keys to exactly match Spatie Schema-org class names
            groups: $/dynamedia/posts/config/forms/schema/groups.yml

        schema_mentions:
            tab: Mentions
            type: repeater
            groups: $/dynamedia/posts/config/forms/schema/groups.yml
