fields:
    body_type:
        tab: dynamedia.posts::lang.common.tabs.body
        label: dynamedia.posts::lang.common.labels.body_type
        type: dropdown
        options:
            repeater_body: dynamedia.posts::lang.common.dropdown.body_type.repeater
            richeditor_body: dynamedia.posts::lang.common.dropdown.body_type.richeditor
            markdown_body: dynamedia.posts::lang.common.dropdown.body_type.markdown
            template_body: dynamedia.posts::lang.common.dropdown.body_type.theme_template

    template_body_options:
        tab: dynamedia.posts::lang.common.tabs.body
        label: Template
        type: dropdown
        dependsOn: body_type
        options: \Dynamedia\Posts\Classes\Helpers\Form::getBodyTemplateOptions

    repeater_body:
        dependsOn: body_type
        type: repeater
        groups: $/dynamedia/posts/config/forms/body/repeater_body/post.yaml

    richeditor_body:
        dependsOn: body_type
        type: richeditor
        size: giant

    markdown_body:
        dependsOn: body_type
        type: markdown
        size: giant
        legacyMode: true

    template_body:
        dependsOn: [body_type, template_body_options]
        type: nestedform
        form:
            tabs:
                defaultTab: "Main"
                fields:




