richeditor_block:
    name: dynamedia.posts::lang.blocks.names.richeditor_block
    description: dynamedia.posts::lang.blocks.descriptions.richeditor_block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/richeditor_block.yaml

html_block:
    name: dynamedia.posts::lang.blocks.names.html_block
    description: dynamedia.posts::lang.blocks.descriptions.html_block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            showPanel: false
            form: $/dynamedia/posts/config/forms/block/html_block.yaml

image_block:
    name: dynamedia.posts::lang.blocks.names.image_block
    description: dynamedia.posts::lang.blocks.descriptions.image_block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            showPanel: false
            form: $/dynamedia/posts/config/forms/image/body.yaml

cms_content_block:
    name: dynamedia.posts::lang.blocks.names.cms_content_block
    description: dynamedia.posts::lang.blocks.descriptions.cms_content_block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            showPanel: false
            form: $/dynamedia/posts/config/forms/block/cms_content_block.yaml

cms_partial_block:
    name: dynamedia.posts::lang.blocks.names.cms_partial_block
    description: dynamedia.posts::lang.blocks.descriptions.cms_partial_block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            showPanel: false
            form: $/dynamedia/posts/config/forms/block/cms_partial_block.yaml
