section:
    name: dynamedia.posts::lang.blocks.names.section
    description: dynamedia.posts::lang.blocks.descriptions.section
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/post_section.yaml

html:
    name: dynamedia.posts::lang.blocks.names.html
    description: dynamedia.posts::lang.blocks.descriptions.html
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/html.yaml

image:
    name: dynamedia.posts::lang.blocks.names.image
    description: dynamedia.posts::lang.blocks.descriptions.image
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/image/body.yaml

cms_content:
    name: dynamedia.posts::lang.blocks.names.cms_content
    description: dynamedia.posts::lang.blocks.descriptions.cms_content
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/cms_content.yaml

cms_partial:
    name: dynamedia.posts::lang.blocks.names.cms_partial
    description: dynamedia.posts::lang.blocks.descriptions.cms_partial
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/cms_partial.yaml

pagebreak:
    name: dynamedia.posts::lang.blocks.names.page_break
    description: dynamedia.posts::lang.blocks.descriptions.page_break
    fields:
        title:
            label: Page break
            placeholder: Page Break
            disabled: true
