# ===================================
#  Relation Behavior Config
# ===================================
tagslugs:
    label: Slugs
    view:
        list: $/dynamedia/posts/models/tagslug/columns.yaml
        toolbarButtons: unlink
    manage:
        form: $/dynamedia/posts/models/tagslug/fields.yaml
        recordsPerPage: 10

translations:
    label: Translations
    view:
        list: $/dynamedia/posts/models/tagtranslation/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/dynamedia/posts/models/tagtranslation/fields.yaml
        recordsPerPage: 10
