# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dynamedia.posts::lang.tags.titles.tag

# Model Form Field configuration
form: $/dynamedia/posts/models/tag/fields.yaml

# Model Class name
modelClass: Dynamedia\Posts\Models\Tag

# Default redirect location
defaultRedirect: dynamedia/posts/tags

# Create page
create:
    title: backend::lang.form.create_title
    redirect: dynamedia/posts/tags/update/:id
    redirectClose: dynamedia/posts/tags

# Update page
update:
    title: backend::lang.form.update_title
    redirect: dynamedia/posts/tags
    redirectClose: dynamedia/posts/tags

# Preview page
preview:
    title: backend::lang.form.preview_title
