tabs:
    fields:
        banner:
            tab: dynamedia.posts::lang.images.tabs.banner
            type: nestedform
            usePanelStyles: true
            showPanel: true
            form: $/dynamedia/posts/config/forms/image/banner.yaml
        social:
            tab: dynamedia.posts::lang.images.tabs.social
            type: nestedform
            usePanelStyles: true
            showPanel: true
            form: $/dynamedia/posts/config/forms/image/social.yaml
